### PR TITLE
Back button is added in components/Post.vue to navigate easily

### PR DESCRIPTION
**Pull request by nullRefErr**

### CODE REVIEW

**Comment by viko16** [comment]
Thank @ErenYatkin for your contribution.

But I don't think the back button is necessary. The user can go back through the browser or click the top title bar to return to the home page. So I don't think it is necessary to add a back button for each article, which does not seem to meet user habits.

Welcome to continue the discussion.

**Comment by nullRefErr** [comment]
When I first run the project and looked here and there then felt something is missing. In the current state of web "gestures" are habits of users but desktop browsers stil do not support it. In my opinion adding a "Back" button can be useful.

**Comment by viko16** [comment]
Yes, I know what you mean now.

But to keep this theme simple, I would not expect to add an extra button to the page, I hope you can understand.

**Comment by ErenYatkin** [comment]
That's okay, it was just an opinion. :)

**Comment by nullRefErr** [comment]
That's okay, it was just an opinion. :)

**Pull request closed without merging**
